from enum import Enum

class MessageType(Enum):
	JOIN_REQUEST = "JOIN_REQUEST"
	PEER_LIST = "PEER_LIST"

	PING = "PING"
	PONG = "PONG"

	SENSOR_UPDATE = "SENSOR_UPDATE"
	GOSSIP_STATE = "GOSSIP_STATE"

	FULL_SYNC_REQUEST = "FULL_SYNC_REQUEST"
	FULL_SYNC_RESPONSE = "FULL_SYNC_RESPONSE"

	ERROR = "ERROR"
	ACK = "ACK"
